CREATE TABLE IF NOT EXISTS posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule34hub_id    BIGINT UNIQUE,
    rule34_api_id   BIGINT,
    file_url        TEXT,
    cdn_url         TEXT,
    thumb_cdn       TEXT,
    media_type      TEXT DEFAULT 'image',
    width           INTEGER,
    height          INTEGER,
    source          TEXT,
    status          TEXT DEFAULT 'resolved',
    resolved_by     TEXT,
    hub_url         TEXT,
    source_type     TEXT DEFAULT 'rule34',
    external_id     TEXT,
    source_meta     TEXT DEFAULT '{}',
    media_category  TEXT DEFAULT 'library',
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tags (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id  BIGINT NOT NULL REFERENCES tags(id)  ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE IF NOT EXISTS tag_groups (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name TEXT NOT NULL,
    tag_name   TEXT NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_tag_groups_name ON tag_groups(group_name);
CREATE INDEX IF NOT EXISTS idx_tag_groups_tag  ON tag_groups(tag_name);

CREATE TABLE IF NOT EXISTS collections (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    search_tags TEXT DEFAULT '[]',
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS collection_review (
    collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    post_id       BIGINT NOT NULL REFERENCES posts(id)       ON DELETE CASCADE,
    PRIMARY KEY (collection_id, post_id)
);
CREATE INDEX IF NOT EXISTS idx_collection_review_col ON collection_review(collection_id);

CREATE TABLE IF NOT EXISTS collection_posts (
    collection_id BIGINT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    post_id       BIGINT NOT NULL REFERENCES posts(id)       ON DELETE CASCADE,
    position      INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (collection_id, post_id)
);

CREATE TABLE IF NOT EXISTS selections (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT,
    post_ids   TEXT NOT NULL DEFAULT '[]',
    is_saved   INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name        TEXT UNIQUE NOT NULL,
    last_fetched_at DOUBLE PRECISION,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feed_posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule34_post_id  BIGINT UNIQUE NOT NULL,
    file_url        TEXT,
    preview_url     TEXT,
    media_type      TEXT DEFAULT 'image',
    tags            TEXT DEFAULT '[]',
    status          TEXT DEFAULT 'unseen',
    matched_subs    TEXT DEFAULT '[]',
    post_date       TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS source_subscriptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind     TEXT NOT NULL,
    url             TEXT NOT NULL UNIQUE,
    label           TEXT,
    enabled         INTEGER NOT NULL DEFAULT 1,
    last_fetched_at DOUBLE PRECISION,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ext_feed_posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind     TEXT NOT NULL,
    source_key      TEXT NOT NULL,
    source_url      TEXT,
    file_url        TEXT,
    preview_url     TEXT,
    media_type      TEXT DEFAULT 'image',
    media_category  TEXT DEFAULT 'external',
    title           TEXT,
    tags            TEXT DEFAULT '[]',
    source_meta     TEXT DEFAULT '{}',
    status          TEXT DEFAULT 'unseen',
    post_date       TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(source_kind, source_key)
);

CREATE INDEX IF NOT EXISTS idx_posts_media_type      ON posts(media_type);
CREATE INDEX IF NOT EXISTS idx_posts_media_category  ON posts(media_category);
CREATE INDEX IF NOT EXISTS idx_post_tags_tag         ON post_tags(tag_id);
CREATE INDEX IF NOT EXISTS idx_post_tags_post        ON post_tags(post_id);
CREATE INDEX IF NOT EXISTS idx_feed_status           ON feed_posts(status);
CREATE INDEX IF NOT EXISTS idx_ext_feed_status       ON ext_feed_posts(status);
CREATE INDEX IF NOT EXISTS idx_source_subs_kind      ON source_subscriptions(source_kind);
